# SPDX-License-Identifier: Apache-2.0

# Try to use the libclang that comes with Xcode.
#
# This is almost certainly an ill-advised thing to do, but
# it does avoid having to install llvm from homebrew (or from
# source).
#
# The really ugly part is that you have to obtain a copy of
# the libclang header files from somewhere. Becaue libclang
# is supposed to provide a stable interface, I'm hoping that
# we'll usually get away with this.
#
## Deciding which headers to copy
#
# Look at the output of clang --version; it will print something
# like "Apple clang version 15.0.0 (clang-1500.3.9.4)"
# 
# This looks like it might matche the tag llvmorg-15.0.0 in the
# https://github.com/llvm/llvm-project repository.
#
# So, it makes sense to try grabbing the libclang include files from
# https://github.com/llvm/llvm-project/tree/llvmorg-15.0.0/clang/include/clang-c
#
# Copy all those headers into ./include/clang-c and then hope
# for the best.
#
# If this doesn't work, bite the bullet and install llvm from
# homebrew or by hand.

# The library directory that contains the Xcode-bundled libclang.
# With only the Command Line Tools selected, the toolchain path has no
# libclang.dylib; it lives in <CLT>/usr/lib, and a full Xcode.app is a last resort.
TOOLCHAIN_LIBDIR=$(shell xcrun --show-toolchain-path)/usr/lib
CLT_LIBDIR=$(shell xcode-select --print-path)/usr/lib
XCODE_LIBDIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
EXTRA_LIBDIR=$(firstword $(dir $(wildcard $(TOOLCHAIN_LIBDIR)/libclang.dylib $(CLT_LIBDIR)/libclang.dylib $(XCODE_LIBDIR)/libclang.dylib)))
ifeq ($(EXTRA_LIBDIR),)
  $(error libclang.dylib not found under $(TOOLCHAIN_LIBDIR), $(CLT_LIBDIR) or $(XCODE_LIBDIR))
endif

INCDIR=include

CFLAGS=-Iinclude
LDFLAGS=-rpath $(EXTRA_LIBDIR) -L $(EXTRA_LIBDIR)
OBJS=ffigen5.o

all:	$(OBJS)
	$(CC) $(LDFLAGS) -lclang $(OBJS) -o ffigen5

clean:
	rm -f ffigen5 *.o
